// Auto-generated flag mappings for Africa region
// Total timezones: 54

pub fn get_flag(city_name: &str) -> Option<&'static str> {
    match city_name {
        "Abidjan" => Some("🇨🇮"),
        "Accra" => Some("🇬🇭"),
        "Addis Ababa" => Some("🇪🇹"),
        "Algiers" => Some("🇩🇿"),
        "Asmara" => Some("🇪🇷"),
        "Asmera" => Some("🇪🇷"),
        "Bamako" => Some("🇲🇱"),
        "Bangui" => Some("🇨🇫"),
        "Banjul" => Some("🇬🇲"),
        "Bissau" => Some("🇬🇼"),
        "Blantyre" => Some("🇲🇼"),
        "Brazzaville" => Some("🇨🇬"),
        "Bujumbura" => Some("🇧🇮"),
        "Cairo" => Some("🇪🇬"),
        "Casablanca" => Some("🇲🇦"),
        "Ceuta" => Some("🇪🇸"),
        "Conakry" => Some("🇬🇳"),
        "Dakar" => Some("🇸🇳"),
        "Dar es Salaam" => Some("🇹🇿"),
        "Djibouti" => Some("🇩🇯"),
        "Douala" => Some("🇨🇲"),
        "El Aaiun" => Some("🇲🇦"),
        "Freetown" => Some("🇸🇱"),
        "Gaborone" => Some("🇧🇼"),
        "Harare" => Some("🇿🇼"),
        "Johannesburg" => Some("🇿🇦"),
        "Juba" => Some("🇸🇸"),
        "Kampala" => Some("🇺🇬"),
        "Khartoum" => Some("🇸🇩"),
        "Kigali" => Some("🇷🇼"),
        "Kinshasa" => Some("🇨🇩"),
        "Lagos" => Some("🇳🇬"),
        "Libreville" => Some("🇬🇦"),
        "Lome" => Some("🇹🇬"),
        "Luanda" => Some("🇦🇴"),
        "Lubumbashi" => Some("🇨🇩"),
        "Lusaka" => Some("🇿🇲"),
        "Malabo" => Some("🇬🇶"),
        "Maputo" => Some("🇲🇿"),
        "Maseru" => Some("🇱🇸"),
        "Mbabane" => Some("🇸🇿"),
        "Mogadishu" => Some("🇸🇴"),
        "Monrovia" => Some("🇱🇷"),
        "Nairobi" => Some("🇰🇪"),
        "Ndjamena" => Some("🇹🇩"),
        "Niamey" => Some("🇳🇪"),
        "Nouakchott" => Some("🇲🇷"),
        "Ouagadougou" => Some("🇧🇫"),
        "Porto-Novo" => Some("🇧🇯"),
        "Sao Tome" => Some("🇸🇹"),
        "Timbuktu" => Some("🌐"),
        "Tripoli" => Some("🇱🇾"),
        "Tunis" => Some("🇹🇳"),
        "Windhoek" => Some("🇳🇦"),
        _ => None,
    }
}
