// Auto-generated flag mappings for Europe region
// Total timezones: 64

pub fn get_flag(city_name: &str) -> Option<&'static str> {
    match city_name {
        "Amsterdam" => Some("🇳🇱"),
        "Andorra" => Some("🇦🇩"),
        "Astrakhan" => Some("🇷🇺"),
        "Athens" => Some("🇬🇷"),
        "Belfast" => Some("🇬🇧"),
        "Belgrade" => Some("🇷🇸"),
        "Berlin" => Some("🇩🇪"),
        "Bratislava" => Some("🇸🇰"),
        "Brussels" => Some("🇧🇪"),
        "Bucharest" => Some("🇷🇴"),
        "Budapest" => Some("🇭🇺"),
        "Busingen" => Some("🇩🇪"),
        "Chisinau" => Some("🇲🇩"),
        "Copenhagen" => Some("🇩🇰"),
        "Dublin" => Some("🇮🇪"),
        "Gibraltar" => Some("🇬🇮"),
        "Guernsey" => Some("🇬🇬"),
        "Helsinki" => Some("🇫🇮"),
        "Isle of Man" => Some("🇮🇲"),
        "Istanbul" => Some("🇹🇷"),
        "Jersey" => Some("🇯🇪"),
        "Kaliningrad" => Some("🇷🇺"),
        "Kiev" => Some("🇺🇦"),
        "Kirov" => Some("🇷🇺"),
        "Kyiv" => Some("🇺🇦"),
        "Lisbon" => Some("🇵🇹"),
        "Ljubljana" => Some("🇸🇮"),
        "London" => Some("🇬🇧"),
        "Luxembourg" => Some("🇱🇺"),
        "Madrid" => Some("🇪🇸"),
        "Malta" => Some("🇲🇹"),
        "Mariehamn" => Some("🇦🇽"),
        "Minsk" => Some("🇧🇾"),
        "Monaco" => Some("🇲🇨"),
        "Moscow" => Some("🇷🇺"),
        "Nicosia" => Some("🇨🇾"),
        "Oslo" => Some("🇳🇴"),
        "Paris" => Some("🇫🇷"),
        "Podgorica" => Some("🇲🇪"),
        "Prague" => Some("🇨🇿"),
        "Riga" => Some("🇱🇻"),
        "Rome" => Some("🇮🇹"),
        "Samara" => Some("🇷🇺"),
        "San Marino" => Some("🇸🇲"),
        "Sarajevo" => Some("🇧🇦"),
        "Saratov" => Some("🇷🇺"),
        "Simferopol" => Some("🇷🇺"),
        "Skopje" => Some("🇲🇰"),
        "Sofia" => Some("🇧🇬"),
        "Stockholm" => Some("🇸🇪"),
        "Tallinn" => Some("🇪🇪"),
        "Tirane" => Some("🇦🇱"),
        "Tiraspol" => Some("🇲🇩"),
        "Ulyanovsk" => Some("🇷🇺"),
        "Uzhgorod" => Some("🇺🇦"),
        "Vaduz" => Some("🇱🇮"),
        "Vatican" => Some("🇻🇦"),
        "Vienna" => Some("🇦🇹"),
        "Vilnius" => Some("🇱🇹"),
        "Volgograd" => Some("🇷🇺"),
        "Warsaw" => Some("🇵🇱"),
        "Zagreb" => Some("🇭🇷"),
        "Zaporozhye" => Some("🇺🇦"),
        "Zurich" => Some("🇨🇭"),
        _ => None,
    }
}
