// Auto-generated flag mappings for Pacific region
// Total timezones: 44

pub fn get_flag(city_name: &str) -> Option<&'static str> {
    match city_name {
        "Apia" => Some("🇼🇸"),
        "Auckland" => Some("🇳🇿"),
        "Bougainville" => Some("🇵🇬"),
        "Chatham" => Some("🇳🇿"),
        "Chuuk" => Some("🇫🇲"),
        "Easter" => Some("🇨🇱"),
        "Efate" => Some("🇻🇺"),
        "Enderbury" => Some("🇰🇮"),
        "Fakaofo" => Some("🇹🇰"),
        "Fiji" => Some("🇫🇯"),
        "Funafuti" => Some("🇹🇻"),
        "Galapagos" => Some("🇪🇨"),
        "Gambier" => Some("🇵🇫"),
        "Guadalcanal" => Some("🇸🇧"),
        "Guam" => Some("🇬🇺"),
        "Honolulu" => Some("🇺🇸"),
        "Johnston" => Some("🌐"),
        "Kanton" => Some("🇰🇮"),
        "Kiritimati" => Some("🇰🇮"),
        "Kosrae" => Some("🇫🇲"),
        "Kwajalein" => Some("🇲🇭"),
        "Majuro" => Some("🇲🇭"),
        "Marquesas" => Some("🇵🇫"),
        "Midway" => Some("🌐"),
        "Nauru" => Some("🇳🇷"),
        "Niue" => Some("🇳🇺"),
        "Norfolk" => Some("🇳🇫"),
        "Noumea" => Some("🇳🇨"),
        "Pago Pago" => Some("🇦🇸"),
        "Palau" => Some("��🇼"),
        "Pitcairn" => Some("🇵🇳"),
        "Pohnpei" => Some("🇫🇲"),
        "Ponape" => Some("🇫🇲"),
        "Port Moresby" => Some("🇵🇬"),
        "Rarotonga" => Some("🇨🇰"),
        "Saipan" => Some("🇲🇵"),
        "Samoa" => Some("🇼🇸"),
        "Tahiti" => Some("🇵🇫"),
        "Tarawa" => Some("🇰🇮"),
        "Tongatapu" => Some("🇹🇴"),
        "Truk" => Some("🇫🇲"),
        "Wake" => Some("🌐"),
        "Wallis" => Some("🇼🇫"),
        "Yap" => Some("🇫🇲"),
        _ => None,
    }
}
